function sd  = rotor_dirs

sr            = rotor_root;

sd  = { ...
        fullfile(sr,'common'), ...
        fullfile(sr,'RotorData'), ...
        fullfile(sr,'Damping'), ...
        fullfile(sr,'FourierSeries'), ...
        fullfile(sr,'LCE'),...
        fullfile(sr,'MBC'), ...
};